//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Drawing;
    using Utilitarios.Extencions;
    using Utilitarios.Classes;
    using Utilitarios.Enumerators;

    public partial class Produto
    {
        public long Id { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> CodigoProduto { get; set; }
        public Nullable<long> MarcaId { get; set; }
        public Nullable<decimal> ValorProduto { get; set; }
        public Nullable<byte> Tipo { get; set; }
        public Nullable<int> Estoque { get; set; }
        public Nullable<decimal> ValorCompra { get; set; }
        public string Observacao { get; set; }
        public byte[] Imagem { get; set; }
       
        public virtual Marca Marca { get; set; }

        public virtual String MarcaNome { get { return this.Marca.IsNull() ? "" : this.Marca.Nome; } }
        public virtual ETipoProduto ETipo { get { return this.Tipo.HasValue ? (ETipoProduto)this.Tipo : ETipoProduto.Padrao; } set { this.Tipo = (byte)value; } }
        public virtual String ValorProdutoFormatado { get { return ValorProduto.Value.ToString("C"); } }
        public virtual String CodigoDescricao { get { return this.CodigoProduto.ToString() + " - " + this.Descricao; } }
        public virtual String MarcaDescricao { get { return this.MarcaNome + " - " + this.Descricao; } }
        public virtual Image ImagemConvertida
        {
            get
            {
                if (this.Imagem.IsNotNull() && this.Imagem.Length > 0)
                    return Util.GetImage(this.Imagem);
                else
                    return null;
            }
        }
    }
}
